# Generated by Django 4.0.4 on 2023-09-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_worktime',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_worktime',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
