# Generated by Django 4.0.4 on 2023-09-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0003_alter_user_breaktime_user_alter_user_worktime_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('permission', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user_breaktime',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_app.user'),
        ),
        migrations.AlterField(
            model_name='user_worktime',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule_app.user'),
        ),
    ]
