# Generated by Django 4.0.4 on 2023-09-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0006_rename_clock_in_user_breaktime_break_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_breaktime',
            name='break_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_breaktime',
            name='break_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
