<<<<<<< HEAD
# Generated by Django 4.0.4 on 2023-10-17 03:55
=======
# Generated by Django 4.0.4 on 2023-10-17 02:09
>>>>>>> main

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0009_user_breaktime_date'),
        ('schedule_app', '0009_user_schedule'),
    ]

    operations = [
    ]
