# Generated by Django 4.0.4 on 2023-11-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0012_user_schedule_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_schedule',
            name='department',
            field=models.CharField(choices=[('U', 'Unassigned'), ('P', 'Pharmacist'), ('R', 'Retail'), ('O', 'Office'), ('F', 'Filling'), ('D', 'Dispatch'), ('D/F', 'Dispatch/Filling'), ('C', 'Compounding'), ('DME', 'DME Driver'), ('DE', 'Data Entry'), ('W', 'Warehouse')], default='U', max_length=3),
        ),
    ]
